"""initial

Revision ID: 61d68ca15400
Revises: 
Create Date: 2026-08-07 23:55:08.192758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d68ca15400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_challenges',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('truthtable', sa.Text(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('date'),
    sa.UniqueConstraint('date')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('battle_token', sa.String(length=128), nullable=True),
    sa.Column('moderator', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('creation_timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('battle_statistics',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('battle_type', sa.String(length=128), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('gates', sa.Integer(), nullable=True),
    sa.Column('longest_path', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('creation_timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('inputs', sa.Integer(), nullable=True),
    sa.Column('outputs', sa.Integer(), nullable=True),
    sa.Column('gates', sa.String(length=128), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('started_on', sa.Float(), nullable=True),
    sa.Column('truthtable', sa.Text(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('and_gates', sa.Integer(), nullable=True),
    sa.Column('or_gates', sa.Integer(), nullable=True),
    sa.Column('not_gates', sa.Integer(), nullable=True),
    sa.Column('xor_gates', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.Integer(), nullable=True),
    sa.Column('outputs', sa.Integer(), nullable=True),
    sa.Column('truthtable', sa.Text(length=5000), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(length=5000), nullable=True),
    sa.Column('creation_timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_challenge_statistics',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('circuit', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('gates', sa.Integer(), nullable=True),
    sa.Column('longest_path', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_statistics',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('challenge_id', sa.String(length=128), nullable=True),
    sa.Column('circuit', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=True),
    sa.Column('gates', sa.Integer(), nullable=True),
    sa.Column('longest_path', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('battle_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('circuit_id', sa.String(length=128), nullable=True),
    sa.Column('gates', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('longest_path', sa.Integer(), nullable=True),
    sa.Column('submission_on', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('battle_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('challenge_statistics')
    op.drop_table('daily_challenge_statistics')
    op.drop_table('challenges')
    op.drop_table('battles')
    op.drop_table('battle_statistics')
    op.drop_table('users')
    op.drop_table('daily_challenges')
    # ### end Alembic commands ###
